site_description: mypUI - 基于uniapp，快速开发原生APP/MP/H5的组件库与工具集
root_domain: mypui.fekit.cn
vue_version: 2.5.16
special_sponsors:
  - url: '#'
    img: small-school.png
    name: 小学通
    description: 上小学通云校，学习小学内容。
  - url: https://mcui.fekit.cn/?c=mypui
    img: mcui.png
    ad_img: mcui.png
    name: mcui
    description: 通过MCUI丰富的组件库、插件库可以非常方便的设计和实现精美的页面与高性能的网站框架。
